admin_area:
    resource: "@SonataAdminBundle/Resources/config/routing/sonata_admin.xml"
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/security.xml"

painting:
    resource: "@PaintingBundle/Controller/"
    type:     annotation
    prefix:   /galerie

blog:
    resource: "@BlogBundle/Controller/"
    type:     annotation
    prefix:   /blog

bio:
    resource: "@BioBundle/Controller/"
    type:     annotation
    prefix:   /biographie

app:
    resource: "@AppBundle/Controller/"
    type:     annotation