services:
    blog.admin.blog:
        class: BlogBundle\Admin\BlogAdmin
        arguments: [~, BlogBundle\Entity\Blog, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Blog }
