services:
    admin.biographie:
        class: AppBundle\Admin\Biographie
        arguments: [~, AppBundle\Entity\Biographie, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Biographie }

    admin.blog:
        class: AppBundle\Admin\Blog
        arguments: [~, AppBundle\Entity\Blog, AppBundle:BlogAdmin]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Blog }
        calls:
            - [ setTemplate, [edit, AppBundle:Admin:blog_edit.html.twig]]

    admin.galerie:
        class: AppBundle\Admin\Galerie
        arguments: [~, AppBundle\Entity\Galerie, SonataAdminBundle:CRUD]
        tags:
            - { name: sonata.admin, manager_type: orm, group: admin, label: Galerie }
